M12:
  SegmentCom:
    # SegmentCom writeKey
    writeKey: PLEASE_PROVIDE_SEGMENT_WRITE_KEY_HERE

    # Segment client options (that client which connects with Segment API)
    clientOptions:
      consumer: fork_curl
      debug: FALSE

    flushImmediatelyWhenInCLI: TRUE
